name: whatsapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  country_picker: ^2.0.23
  flutter_riverpod: ^2.4.9
  image_picker: ^1.0.7
  flutter_contacts: ^1.1.7+1
  uuid: ^3.0.1
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  emoji_picker_flutter: ^1.6.3
  enough_giphy_flutter: ^0.4.1
  flutter_sound: ^9.2.13
  permission_handler: ^11.2.0
  path_provider: ^2.1.2
  audioplayers: ^5.2.1
  swipe_to: ^1.0.5
  story_view: ^0.16.0
  agora_uikit:
  video_player: ^2.6.0
  flutter_profile_picture: ^2.0.0
  cached_video_player: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
flutter:
  uses-material-design: true
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

